disabled_rules:
  - file_length
  - function_body_length
  - function_parameter_count
  - identifier_name

opt_in_rules: # some rules are only opt-in
  - anyobject_protocol
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - comma_inheritance
  - empty_count
  - empty_collection_literal
  - empty_string
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - function_default_parameter_at_end
  - implicitly_unwrapped_optional
  - indentation_width
  - last_where
  - literal_expression_end_indentation
  - object_literal
  - operator_usage_whitespace
  - raw_value_for_camel_cased_codable_enum
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - sorted_imports
  - toggle_bool
  - trailing_closure
  - typesafe_array_init
  - unowned_variable_capture
  - unused_declaration
  - unused_import
  - weak_delegate
  - yoda_condition

line_length:
  ignores_comments: true

custom_rules:
  force_https:
    name: "Force HTTPS over HTTP"
    regex: "((?i)http(?!s))"
    match_kinds: string
    message: "HTTPS should be favored over HTTP"
    severity: warning
