platform :ios, '9.0'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
  pod 'Catch', :path => '../'

  target 'ExampleUITests' do
    # Pods for testing
  end

end
