name: Run Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v2
    - name: Build SDK
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild build-for-testing -scheme Catch -destination "platform=iOS Simulator,OS=latest,name=iPhone 12" | xcpretty
    - name: Run Unit Tests
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild test-without-building -scheme Catch -destination "platform=iOS Simulator,OS=latest,name=iPhone 12" | xcpretty
